server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://172.17.202.146:5432/portal_test?currentSchema=public
    username: postgres
    password: qes123456
    druid:
      filter:
        wall:
          enabled: true
          db-type: postgresql
          config:
            drop-table-allow: true
            truncate-allow: true
            alter-table-allow: true
            create-table-allow: true
    driver-class-name: org.postgresql.Driver


############################### mybatis-plus start #################################
mybatis-plus:
  # 启动时是否检查MyBatis XML文件是否存在
  check-config-location: true
  # MyBatis原生配置
  configuration:
    # 字段名称下划线转驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 全局默认主键类型
      id-type: id_worker
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  # mapper xml映射路径
  mapper-locations: classpath*:mapper/**/*Mapper.xml
################################ mybatis-plus end ##################################